import test from 'node:test';import assert from 'node:assert/strict';import{analyzeImport}from'../services/importService.ts';import{parseCsv,parseJson,parseFile}from'../services/fileParser.ts';import * as XLSX from 'xlsx';
test('filename does not determine JSON schema',async()=>{const c=JSON.stringify([{username:'@Alpha',fullName:'Alpha',profilePicUrl:'https://x.test/a.jpg'},{username:null,fullName:'No IG',profilePicUrl:'https://x.test/b.jpg'}]);const a=await analyzeImport(c,'random-name.any',async()=>new Set());assert.equal(a.format,'JSON');assert.equal(a.total,2);assert.equal(a.withInstagram,1);assert.equal(a.withoutInstagram,1);assert.equal(a.newRecords,2);});
test('recognizes supplied QModels-style CSV headers independent of filename',async()=>{const c='Letter,Model Name,Instagram Username,Instagram Link,Babepedia Source,ProfilePicUrl\nQ,"Q,O",@qorianka,https://instagram.com/qorianka,https://example.test/source,https://example.test/q.jpg';const a=await analyzeImport(c,'anything.csv',async()=>new Set());assert.equal(a.format,'CSV');assert.equal(a.total,1);assert.equal(a.processable[0].instagramUsername,'qorianka');assert.equal(a.processable[0].modelName,'Q,O');assert.equal(a.processable[0].letter,'Q');});
test('supports quoted CSV, BOM, CRLF and N/A values',async()=>{const c='\uFEFFModel Name,Instagram Username,Notes\r\n"Person, One",N/A,"hello, world"\r\nSecond,@SECOND,"note"';const a=await analyzeImport(c,'renamed.txt',async()=>new Set());assert.equal(a.format,'CSV');assert.equal(a.total,2);assert.equal(a.withoutInstagram,1);assert.equal(a.processable.find(r=>r.modelName==='Second')?.instagramUsername,'second');});
test('supports JSONL and NDJSON',()=>{assert.equal(parseFile('{"username":"one"}\n{"username":"two"}','backup.jsonl').rows.length,2);assert.equal(parseFile('{"username":"one"}\n{"username":"two"}','backup.ndjson').rows.length,2);});
test('supports TSV and headerless CSV',()=>{assert.deepEqual(parseFile('username\tone\nusername\ttwo','x.tsv').rows,[{column_1:'username',column_2:'one'},{column_1:'username',column_2:'two'}]);assert.deepEqual(parseCsv('alpha,beta\n@alpha,@beta'),[{column_1:'alpha',column_2:'beta'},{column_1:'@alpha',column_2:'@beta'}]);});
test('detects JSON from misleading TXT content',()=>{assert.equal(parseFile('[{"username":"x"}]','data.txt').format,'JSON');});
test('malformed JSON and CSV produce actionable errors',()=>{assert.throws(()=>parseJson('{bad'),/Malformed JSON/);assert.throws(()=>parseCsv('username\n"bad'),/Malformed delimited file/);});

test('detects CSV and TSV from content when extension is misleading',()=>{assert.equal(parseFile('Model Name,Instagram Username\nA,@a','renamed.txt').format,'CSV');assert.equal(parseFile('Model Name\tInstagram Username\nB\t@b','renamed.txt').format,'TSV');});
test('detects an imported username change without depending on filename',async()=>{const c='Letter,Model Name,Instagram Username,Babepedia Source\nQ,Example Person,@new_handle,https://example.test/person';const a=await analyzeImport(c,'renamed-anything.csv',async()=>new Set(),undefined,async candidates=>{assert.equal(candidates[0].username,'new_handle');assert.equal(candidates[0].model_name,'Example Person');return[{account_id:42,old_username:'old_handle',new_username:'new_handle'}];});assert.equal(a.usernameChanges.length,1);assert.deepEqual(a.usernameChanges[0],{accountId:42,oldUsername:'old_handle',newUsername:'new_handle',modelName:'Example Person'});assert.equal(a.newRecords,0);assert.equal(a.updatedRecords,1);});

test('imports X usernames and treats NONE as unavailable',async()=>{const c='Letter,Model Name,Instagram Username,X Username,X Link,ProfilePicUrl\nA,Alpha,N/A,@alpha_x,,https://example.test/a.jpg\nB,Beta,N/A,NONE,N/A,https://example.test/b.jpg';const a=await analyzeImport(c,'models.csv',async()=>new Set());assert.equal(a.total,2);assert.equal(a.withInstagram,0);assert.equal(a.processable.length,2);assert.equal(a.processable[0].xUsername,'alpha_x');assert.equal(a.processable[0].xUrl,'https://x.com/alpha_x/');assert.equal(a.processable[1].xUsername,null);assert.equal(a.processable[1].xUrl,null);});

test('imports TikTok usernames and links independently',async()=>{const c='Letter,Model Name,Instagram Username,X Username,TikTok Username,TikTok Link\nA,Alpha,N/A,N/A,@alpha_tok,\nB,Beta,N/A,N/A,N/A,https://www.tiktok.com/@beta_tok';const a=await analyzeImport(c,'renamed.data',async()=>new Set());assert.equal(a.total,2);assert.equal(a.processable[0].tiktokUsername,'alpha_tok');assert.equal(a.processable[0].tiktokUrl,'https://www.tiktok.com/@alpha_tok');assert.equal(a.processable[1].tiktokUsername,'beta_tok');assert.equal(a.processable[1].tiktokUrl,'https://www.tiktok.com/@beta_tok');});


test('supports the supplied QModels JSON shape and encoded TikTok URLs',async()=>{const c=JSON.stringify([{username:'qamaraltaiy',fullName:'Qamar Altaey',externalUrl:'https://instagram.com/qamaraltaiy',xUrl:null,tiktokUrl:'https://www.tiktok.com/%40qamar_altaey',profilePicUrl:'https://www.babepedia.com/pics/Qamar%20Altaey_thumb3.jpg',instagramUsername:'qamaraltaiy',xUsername:null,tiktokUsername:'qamar_altaey',letter:'Q',sourceUrl:'https://www.babepedia.com/babe/Qamar_Altaey',notes:'Source: https://www.babepedia.com/babe/Qamar_Altaey'}]);const a=await analyzeImport(c,'QModels.anything',async()=>new Set());assert.equal(a.format,'JSON');assert.equal(a.total,1);assert.equal(a.processable[0].modelName,'Qamar Altaey');assert.equal(a.processable[0].instagramUsername,'qamaraltaiy');assert.equal(a.processable[0].tiktokUsername,'qamar_altaey');assert.equal(a.processable[0].tiktokUrl,'https://www.tiktok.com/%40qamar_altaey');assert.equal(a.processable[0].sourceUrl,'https://www.babepedia.com/babe/Qamar_Altaey');});
test('parses XLSX content as base64 independent of filename',()=>{const wb=XLSX.utils.book_new();const ws=XLSX.utils.aoa_to_sheet([['Model Name','Instagram Username','X Username'],['Alpha','@alpha','@alpha_x']]);XLSX.utils.book_append_sheet(wb,ws,'Models');const b64=XLSX.write(wb,{type:'base64',bookType:'xlsx'});const parsed=parseFile(b64,'renamed.data','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');assert.equal(parsed.format,'XLSX');assert.equal(parsed.rows.length,1);assert.equal(parsed.rows[0]['Instagram Username'],'@alpha');});

test('does not collapse records with no identity fields',async()=>{const c='Notes,Other Field\nalpha,one\nbeta,two';const a=await analyzeImport(c,'data.csv',async()=>new Set());assert.equal(a.processable.length,2);assert.notEqual(a.processable[0].identityKey,a.processable[1].identityKey);});

test('parses Instagram followers JSON by content, not filename',async()=>{const c=JSON.stringify([{title:'',media_list_data:[],string_list_data:[{href:'https://www.instagram.com/alpha.one/ ',value:'alpha.one',timestamp:1700000000}]},{title:'',string_list_data:[{href:'https://www.instagram.com/beta/',value:'beta',timestamp:1700000001}]}]);const a=await analyzeImport(c,'completely-random-name.json',async()=>new Set());assert.equal(a.format,'JSON');assert.equal(a.total,2);assert.deepEqual(a.processable.map(r=>r.instagramUsername),['alpha.one','beta']);assert.equal(a.processable[0].instagramUrl,'https://www.instagram.com/alpha.one/');});
test('parses Instagram following JSON nested under relationships_following',async()=>{const c=JSON.stringify({relationships_following:[{title:'gamma',string_list_data:[{href:'https://www.instagram.com/gamma/',value:'gamma',timestamp:1700000002}]},{title:'delta',string_list_data:[{href:'https://www.instagram.com/delta/',value:'delta',timestamp:1700000003}]}]});const a=await analyzeImport(c,'following-without-standard-name.json',async()=>new Set());assert.equal(a.total,2);assert.equal(a.processable[0].instagramUsername,'gamma');assert.equal(a.processable[1].instagramUsername,'delta');});
test('parses Instagram HTML profile links',async()=>{const c='<html><body><a href="https://www.instagram.com/alpha/">@alpha</a><a href="https://www.instagram.com/beta/">Beta</a></body></html>';const a=await analyzeImport(c,'export-with-random-name.html',async()=>new Set());assert.equal(a.format,'HTML');assert.equal(a.total,2);assert.deepEqual(a.processable.map(r=>r.instagramUsername),['alpha','beta']);});

test('does not treat an unrelated JSON title field as an Instagram export',async()=>{const c=JSON.stringify([{title:'Quarterly Report',value:123},{title:'Another Report',value:456}]);const a=await analyzeImport(c,'random.json',async()=>new Set());assert.equal(a.total,2);assert.equal(a.withInstagram,0);});

test('preserves every pipe-separated ProfilePicUrl image URL',async()=>{const c='Letter,Model Name,Instagram Username,Instagram Link,X Username,X Link,TikTok Username,TikTok Link,Babepedia Source,ProfilePicUrl\nQ,Qamar Altaey,@qamaraltaiy,https://instagram.com/qamaraltaiy,,,,,https://www.babepedia.com/babe/Qamar_Altaey,https://www.babepedia.com/pics/Qamar%20Altaey.jpg | https://www.babepedia.com/pics/Qamar%20Altaey2.jpg | https://www.babepedia.com/pics/Qamar%20Altaey3.jpg | https://www.babepedia.com/pics/Qamar%20Altaey4.jpg';const a=await analyzeImport(c,'anything.csv',async()=>new Set());assert.equal(a.total,1);assert.deepEqual(a.processable[0].profileImageUrls,['https://www.babepedia.com/pics/Qamar%20Altaey.jpg','https://www.babepedia.com/pics/Qamar%20Altaey2.jpg','https://www.babepedia.com/pics/Qamar%20Altaey3.jpg','https://www.babepedia.com/pics/Qamar%20Altaey4.jpg']);assert.equal(a.processable[0].profileImageUrl,a.processable[0].profileImageUrls[0]);});
