import test from 'node:test';import assert from 'node:assert/strict';import{analyzeImport}from'../services/importService.ts';import{parseCsv,parseJson,parseFile}from'../services/fileParser.ts';
test('filename does not determine JSON schema',async()=>{const c=JSON.stringify([{username:'@Alpha',fullName:'Alpha',profilePicUrl:'https://x.test/a.jpg'},{username:null,fullName:'No IG',profilePicUrl:'https://x.test/b.jpg'}]);const a=await analyzeImport(c,'random-name.any',async()=>new Set());assert.equal(a.format,'JSON');assert.equal(a.total,2);assert.equal(a.withInstagram,1);assert.equal(a.withoutInstagram,1);assert.equal(a.newRecords,2);});
test('recognizes supplied QModels-style CSV headers independent of filename',async()=>{const c='Letter,Model Name,Instagram Username,Instagram Link,Babepedia Source,ProfilePicUrl\nQ,"Q,O",@qorianka,https://instagram.com/qorianka,https://example.test/source,https://example.test/q.jpg';const a=await analyzeImport(c,'anything.csv',async()=>new Set());assert.equal(a.format,'CSV');assert.equal(a.total,1);assert.equal(a.processable[0].instagramUsername,'qorianka');assert.equal(a.processable[0].modelName,'Q,O');assert.equal(a.processable[0].letter,'Q');});
test('supports quoted CSV, BOM, CRLF and N/A values',async()=>{const c='\uFEFFModel Name,Instagram Username,Notes\r\n"Person, One",N/A,"hello, world"\r\nSecond,@SECOND,"note"';const a=await analyzeImport(c,'renamed.txt',async()=>new Set());assert.equal(a.format,'CSV');assert.equal(a.total,2);assert.equal(a.withoutInstagram,1);assert.equal(a.processable.find(r=>r.modelName==='Second')?.instagramUsername,'second');});
test('supports JSONL and NDJSON',()=>{assert.equal(parseFile('{"username":"one"}\n{"username":"two"}','backup.jsonl').rows.length,2);assert.equal(parseFile('{"username":"one"}\n{"username":"two"}','backup.ndjson').rows.length,2);});
test('supports TSV and headerless CSV',()=>{assert.deepEqual(parseFile('username\tone\nusername\ttwo','x.tsv').rows,[{column_1:'username',column_2:'one'},{column_1:'username',column_2:'two'}]);assert.deepEqual(parseCsv('alpha,beta\n@alpha,@beta'),[{column_1:'alpha',column_2:'beta'},{column_1:'@alpha',column_2:'@beta'}]);});
test('detects JSON from misleading TXT content',()=>{assert.equal(parseFile('[{"username":"x"}]','data.txt').format,'JSON');});
test('malformed JSON and CSV produce actionable errors',()=>{assert.throws(()=>parseJson('{bad'),/Malformed JSON/);assert.throws(()=>parseCsv('username\n"bad'),/Malformed delimited file/);});

test('detects CSV and TSV from content when extension is misleading',()=>{assert.equal(parseFile('Model Name,Instagram Username\nA,@a','renamed.txt').format,'CSV');assert.equal(parseFile('Model Name\tInstagram Username\nB\t@b','renamed.txt').format,'TSV');});
test('detects an imported username change without depending on filename',async()=>{const c='Letter,Model Name,Instagram Username,Babepedia Source\nQ,Example Person,@new_handle,https://example.test/person';const a=await analyzeImport(c,'renamed-anything.csv',async()=>new Set(),undefined,async candidates=>{assert.equal(candidates[0].username,'new_handle');assert.equal(candidates[0].model_name,'Example Person');return[{account_id:42,old_username:'old_handle',new_username:'new_handle'}];});assert.equal(a.usernameChanges.length,1);assert.deepEqual(a.usernameChanges[0],{accountId:42,oldUsername:'old_handle',newUsername:'new_handle',modelName:'Example Person'});assert.equal(a.newRecords,0);assert.equal(a.updatedRecords,1);});

test('imports X usernames and treats NONE as unavailable',async()=>{const c='Letter,Model Name,Instagram Username,X Username,X Link,ProfilePicUrl\nA,Alpha,N/A,@alpha_x,,https://example.test/a.jpg\nB,Beta,N/A,NONE,N/A,https://example.test/b.jpg';const a=await analyzeImport(c,'models.csv',async()=>new Set());assert.equal(a.total,2);assert.equal(a.withInstagram,0);assert.equal(a.processable.length,2);assert.equal(a.processable[0].xUsername,'alpha_x');assert.equal(a.processable[0].xUrl,'https://x.com/alpha_x/');assert.equal(a.processable[1].xUsername,null);assert.equal(a.processable[1].xUrl,null);});
