import * as XLSX from 'xlsx';
export type ParsedRow=Record<string,unknown>;
export type DetectedFormat='JSON'|'CSV'|'XLSX'|'XLS'|'TSV'|'TXT'|'JSONL'|'NDJSON'|'XML'|'HTML';
export interface ParsedFile{format:DetectedFormat;rows:ParsedRow[];warnings:string[];}
const clean=(s:string)=>s.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n');
const extension=(n:string)=>n.toLowerCase().split('.').pop()||'';
const key=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]/g,'');
function matrix(content:string,delimiter=','){const rows:string[][]=[];let row:string[]=[],v='',q=false;for(let i=0;i<content.length;i++){const c=content[i],n=content[i+1];if(q){if(c==='"'&&n==='"'){v+='"';i++;}else if(c==='"')q=false;else v+=c;continue;}if(c==='"'){if(v.trim())throw new Error('Malformed delimited file: unexpected quote.');q=true;}else if(c===delimiter){row.push(v.trim());v='';}else if(c==='\n'){row.push(v.trim());v='';if(row.some(Boolean))rows.push(row);row=[];}else v+=c;}if(q)throw new Error('Malformed delimited file: missing closing quote.');if(v.length||row.length){row.push(v.trim());if(row.some(Boolean))rows.push(row);}return rows;}
function fromMatrix(rows:string[][]){if(!rows.length)return[];const headerKeys=new Set(['modelname','fullname','displayname','instagramusername','instagramlink','profilepicurl','babepediasource','source','letter','alphabet','notes','xusername','xlink','xurl','twitterusername','twitterlink','twitterurl','tiktokusername','tiktoklink','tiktokurl']);const firstKeys=rows[0].map(key);const looksLikeHeader=firstKeys.some(k=>headerKeys.has(k));const header=looksLikeHeader;const heads=(header?rows[0]:Array.from({length:Math.max(...rows.map(r=>r.length))},(_,i)=>'column_'+(i+1))).map((h,i)=>h||'column_'+(i+1));return (header?rows.slice(1):rows).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??''])));}
function instagramRows(v:unknown):ParsedRow[]{const out:ParsedRow[]=[];const walk=(node:unknown)=>{if(Array.isArray(node)){for(const x of node)walk(x);return;}if(!node||typeof node!=='object')return;const r=node as Record<string,unknown>;const list=r.string_list_data;if(Array.isArray(list)&&list.length){for(const item of list){if(!item||typeof item!=='object')continue;const d=item as Record<string,unknown>;const href=typeof d.href==='string'?d.href:'';const value=typeof d.value==='string'?d.value:'';const title=typeof r.title==='string'?r.title:'';const username=(value||title).trim().replace(/^@+/,'');if(username||href)out.push({'Instagram Username':username||'', 'Instagram Link':href||'', 'Instagram Timestamp':typeof d.timestamp==='number'?d.timestamp:'', 'Instagram Export Record':true});}return;}for(const [key,value] of Object.entries(r)){if(value&&typeof value==='object')walk(value);}};walk(v);const seen=new Set<string>();return out.filter(row=>{const u=String(row['Instagram Username']||'').toLowerCase();const h=String(row['Instagram Link']||'').toLowerCase();const identity=u||h;if(!identity||seen.has(identity))return false;seen.add(identity);return true;});}
function jsonRows(v:unknown):ParsedRow[]{const instagram=instagramRows(v);if(instagram.length)return instagram;if(Array.isArray(v))return v.flatMap(x=>x&&typeof x==='object'&&!Array.isArray(x)?[x as ParsedRow]:typeof x==='string'||typeof x==='number'?[{username:String(x)}]:[]);if(v&&typeof v==='object'){const r=v as Record<string,unknown>;for(const k of Object.keys(r)){if(['models','accounts','users','profiles','data','items','results','records','rows','relationships_following','relationships_followers','followers','following'].includes(k.toLowerCase())){const a=jsonRows(r[k]);if(a.length)return a;}}return[r];}return[];}
export function parseJson(c:string){try{return jsonRows(JSON.parse(clean(c)));}catch{throw new Error('Malformed JSON file. Please check the file format and try again.');}}
export function parseCsv(c:string){return fromMatrix(matrix(clean(c)));} export function parseTsv(c:string){return fromMatrix(matrix(clean(c),'\t'));}
export function parseJsonLines(c:string){const out:ParsedRow[]=[];for(const [i,line] of clean(c).split('\n').entries()){if(!line.trim())continue;try{out.push(...jsonRows(JSON.parse(line)));}catch{throw new Error(`Malformed JSONL/NDJSON at line ${i+1}.`);}}return out;}
export function detectFormat(content:string,fileName:string,mime?:string):DetectedFormat{const e=extension(fileName),t=clean(content).trimStart();if(/^\s*[\[{]/.test(t)){try{JSON.parse(clean(content));return'JSON';}catch{}}if(/^<(!doctype\s+html|html\b)/i.test(t)||/<html[\s>]/i.test(t))return'HTML';if(/^<[^>]+>/.test(t))return'XML';
const firstLine=t.split('\n',1)[0]??'';
if(firstLine.includes('\t'))return'TSV';
if(firstLine.includes(','))return'CSV';if(e==='jsonl')return'JSONL';if(e==='ndjson')return'NDJSON';if(e==='tsv')return'TSV';if(e==='csv')return'CSV';if(e==='xlsx')return'XLSX';if(e==='xls')return'XLS';if(e==='xml')return'XML';if(e==='html'||e==='htm')return'HTML';if(e==='json')return'JSON';if(e==='txt')return'TXT';if(mime?.includes('json'))return'JSON';if(mime?.includes('csv'))return'CSV';if(mime?.includes('spreadsheet'))return'XLSX';if(t.includes('\n')&&firstLine.includes(','))return'CSV';
if(t.includes('\n')&&firstLine.includes('\t'))return'TSV';
if(t.includes(',')||t.includes('\n'))return'CSV';return'TXT';}
function xmlRows(c:string){const out:ParsedRow[]=[];const re=/<(record|item|person|model|account)\b[^>]*>([\s\S]*?)<\/\1>/gi;let m:RegExpExecArray|null;while(m=re.exec(c)){const r:ParsedRow={};const f=/<([A-Za-z_][\w:-]*)\b[^>]*>([\s\S]*?)<\/\1>/g;let x:RegExpExecArray|null;while(x=f.exec(m[2]))r[x[1]]=x[2].replace(/<[^>]+>/g,'').trim();out.push(r);}return out.length?out:[{rawXml:clean(c)}];}
function htmlRows(c:string){const source=clean(c).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ');const out:ParsedRow[]=[];const anchor=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while(m=anchor.exec(source)){const href=m[1].trim(),label=m[2].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const match=href.match(/(?:https?:\/\/)?(?:www\.)?instagram\.com\/([^/?#&\s]+)/i);const username=(match?.[1]||label).replace(/^@+/,'').trim();if(username&&/^[A-Za-z0-9._]{1,30}$/.test(username))out.push({'Instagram Username':username,'Instagram Link':href,'Instagram Export Record':true});}if(out.length)return out;const text=source.replace(/<[^>]+>/g,'\n');return text.split('\n').map(s=>s.trim()).filter(Boolean).map(rawText=>({rawText}));}
export function parseFile(content:string,fileName:string,mime?:string):ParsedFile{const e=extension(fileName);const isSpreadsheet=e==='xlsx'||e==='xls'||mime?.includes('spreadsheet')||mime?.includes('excel');if(isSpreadsheet){const format:DetectedFormat=e==='xls'?'XLS':'XLSX';try{const wb=XLSX.read(content,{type:'base64'});const s=wb.Sheets[wb.SheetNames[0]];return{format,rows:s?XLSX.utils.sheet_to_json<ParsedRow>(s,{defval:''}):[],warnings:[]};}catch{throw new Error(`Unable to parse ${format} spreadsheet. Verify the file is valid.`);}}const format=detectFormat(content,fileName,mime);if(!content.trim())return{format,rows:[],warnings:['The selected file is empty.']};switch(format){case'JSON':return{format,rows:parseJson(content),warnings:[]};case'CSV':return{format,rows:parseCsv(content),warnings:[]};case'TSV':return{format,rows:parseTsv(content),warnings:[]};case'JSONL':case'NDJSON':return{format,rows:parseJsonLines(content),warnings:[]};case'XML':return{format,rows:xmlRows(content),warnings:[]};case'HTML':return{format,rows:htmlRows(content),warnings:['HTML imports preserve extracted text and may require manual mapping.']};case'XLSX':case'XLS':throw new Error('Spreadsheet data must be read as binary/base64.');default:return{format:'TXT',rows:clean(content).split(/\n+/).flatMap(l=>l.split(/[,;\t ]+/)).filter(Boolean).map(username=>({username})),warnings:[]};}}
