import {parseFile,type ParsedRow,type DetectedFormat} from './fileParser';import{normalizeUsername,buildInstagramUrl,isPlaceholderImage}from '../utils/normalization';
export interface ImportRecord{sourceRow:number;modelName:string|null;letter:string|null;instagramUsername:string|null;instagramUrl:string|null;profileImageUrl:string|null;sourceUrl:string|null;notes:string|null;rawData:ParsedRow;identityKey:string;}
export interface UsernameChangePreview{accountId:number;oldUsername:string;newUsername:string;modelName:string|null;}
export interface ImportAnalysis{records:ImportRecord[];processable:ImportRecord[];usernameChanges:UsernameChangePreview[];total:number;newRecords:number;updatedRecords:number;existingRecords:number;duplicatesInFile:number;invalid:number;withoutInstagram:number;withInstagram:number;withImages:number;withoutImages:number;placeholderImages:number;detectedFields:string[];warnings:string[];format:DetectedFormat;}
const k=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,'');const t=(v:unknown)=>v==null?'':String(v).trim();function first(r:ParsedRow,keys:string[]){const m=new Map(Object.entries(r).map(([a,b])=>[k(a),b]));for(const x of keys){const v=t(m.get(k(x)));if(v&& !['n/a','na','null','-'].includes(v.toLowerCase()))return v;}return null;}
function username(r:ParsedRow){const direct=first(r,['Instagram Username','instagram_username','instagramUsername','Instagram','Username','username','handle','user']);const link=first(r,['Instagram Link','Instagram URL','instagram_url','instagramUrl','externalUrl','Profile URL','url','link']);const s=direct||link||'';let u=normalizeUsername(s);if(!direct&&link&&!/instagram\.com\//i.test(link))u='';if(u&&!/^[a-z0-9._]{1,30}$/.test(u))return null;if(u.startsWith('.')||u.endsWith('.')||u.includes('..'))return null;const bad=new Set(['explore','accounts','reels','reel','p','stories','direct','tv']);return u&&!bad.has(u)?u:null;}
export function parseImportFile(c:string,n:string,m?:string){return parseFile(c,n,m);}
export async function analyzeImport(c:string,n:string,findExisting:(u:string[])=>Promise<Set<string>>,m?:string):Promise<ImportAnalysis>{const parsed=parseFile(c,n,m);const records=parsed.rows.map((raw,i)=>{const u=username(raw);const modelName=first(raw,['Model Name','model_name','modelName','Full Name','fullName','Name','name','displayName','display_name']);const letter=first(raw,['Letter','letter','Alphabet']);const profileImageUrl=first(raw,['ProfilePicUrl','profilePicUrl','Profile Image','Profile Image URL','profile_image_url','profileImageUrl','imageUrl','Image URL','image']);const notes=first(raw,['notes','Notes']);const sourceUrl=first(raw,['Babepedia Source','Source','Source URL','source_url','Website'])||(notes?.match(/https?:\/\/\S+/)?.[0]||null);const instagramUrl=first(raw,['Instagram Link','Instagram URL','instagram_url','instagramUrl','externalUrl','Profile URL'])||(u?buildInstagramUrl(u):null);const identityKey=u?`ig:${u}`:`source:${sourceUrl||''}|name:${(modelName||'').toLowerCase()}`;return{sourceRow:i+1,modelName,letter,instagramUsername:u,instagramUrl,profileImageUrl,sourceUrl,notes,rawData:raw,identityKey};});const valid=records.filter(r=>!!r.instagramUsername),seen=new Set<string>();let duplicates=0;const processable:ImportRecord[]=[];for(const r of valid){if(seen.has(r.instagramUsername!))duplicates++;else{seen.add(r.instagramUsername!);processable.push(r);}}const existing=await findExisting(processable.map(r=>r.instagramUsername!));const changes=await (findExisting as any).__findUsernameChanges?.(processable)??[];return{records,processable,usernameChanges:changes.map((x:any)=>{const r=processable.find(p=>p.instagramUsername===x.new_username);return{accountId:x.account_id,oldUsername:x.old_username,newUsername:x.new_username,modelName:r?.modelName??null};}),total:records.length,newRecords:processable.filter(r=>!existing.has(r.instagramUsername!)).length,updatedRecords:processable.filter(r=>existing.has(r.instagramUsername!)).length,existingRecords:existing.size,duplicatesInFile:duplicates,invalid:records.length-valid.length,withoutInstagram:records.length-valid.length,withInstagram:valid.length,withImages:records.filter(r=>!!r.profileImageUrl&&!isPlaceholderImage(r.profileImageUrl)).length,withoutImages:records.filter(r=>!r.profileImageUrl||isPlaceholderImage(r.profileImageUrl)).length,placeholderImages:records.filter(r=>isPlaceholderImage(r.profileImageUrl)).length,detectedFields:Array.from(new Set(parsed.rows.flatMap(r=>Object.keys(r)))),warnings:parsed.warnings,format:parsed.format};}

export interface ImportSummary{total:number;names:string[];newRecords:number;updatedRecords:number;duplicates:number;invalid:number;withInstagram:number;withoutInstagram:number;withImages:number;withoutImages:number;placeholderImages:number;format:DetectedFormat;warnings:string[];}
export function toImportSummary(a:ImportAnalysis):ImportSummary{return{total:a.total,names:a.records.map(r=>r.modelName||r.instagramUsername||'Unnamed').slice(0,20),newRecords:a.newRecords,updatedRecords:a.updatedRecords,duplicates:a.duplicatesInFile,invalid:a.invalid,withInstagram:a.withInstagram,withoutInstagram:a.withoutInstagram,withImages:a.withImages,withoutImages:a.withoutImages,placeholderImages:a.placeholderImages,format:a.format,warnings:a.warnings};}
