import React,{useState}from'react';import{Pressable,ScrollView,StyleSheet,Switch,Text,View,Alert}from'react-native';import{Stack,useRouter}from'expo-router';import{AccountStatus,ACCOUNT_STATUSES,STATUS_LABELS}from'../types/account';import{createBackup,pickBackup,restoreBackup}from'../services/backupService';import{toUserMessage}from'../services/errors';import{hardResetDatabase}from'../database';import type{AppSettings,ThemePreference}from'../services/settingsService';import{APP_VERSION}from'../utils/constants';import{formatDateHuman}from'../utils/normalization';import{useSettings}from'../utils/useSettings';import{useTheme}from'../utils/useTheme';import ConfirmDialog from'../components/ConfirmDialog';
export default function SettingsScreen(){const router=useRouter(),{colors}=useTheme(),{settings,update}=useSettings();const[busy,setBusy]=useState(false),[pending,setPending]=useState<any>(null),[reset,setReset]=useState(false);const action=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();}catch(e){Alert.alert('Error',toUserMessage(e));}finally{setBusy(false);}};
return <ScrollView style={{backgroundColor:colors.background}} contentContainerStyle={s.content}><Stack.Screen options={{title:'Settings'}}/>
<Section title='Appearance' c={colors}><Chips options={[{key:'system',label:'System'},{key:'light',label:'Light'},{key:'dark',label:'Dark'}]} value={settings.theme} onSelect={k=>void update('theme',k as ThemePreference)} c={colors}/></Section>
<Section title='Processing' c={colors}><Toggle label='Auto-next after status' value={settings.autoNext} onChange={v=>void update('autoNext',v)} c={colors}/><Toggle label='Confirm status changes' value={settings.confirmStatusChanges} onChange={v=>void update('confirmStatusChanges',v)} c={colors}/><Text style={{color:colors.text}}>Default filter</Text><Chips options={[{key:'ALL',label:'All'},...ACCOUNT_STATUSES.map(x=>({key:x,label:STATUS_LABELS[x]}))]} value={settings.defaultFilter} onSelect={k=>void update('defaultFilter',k as AppSettings['defaultFilter'])} c={colors}/></Section>
<Section title='Instagram' c={colors}><Toggle label='Prefer Instagram app' value={settings.preferInstagramApp} onChange={v=>void update('preferInstagramApp',v)} c={colors}/><Toggle label='Browser fallback' value={settings.browserFallback} onChange={v=>void update('browserFallback',v)} c={colors}/><Text style={{color:colors.textMuted}}>Opening Instagram is the only Instagram integration. The app never logs in, scrapes, or automates Instagram.</Text></Section>
<Section title='Data' c={colors}><Button label='Export accounts' onPress={()=>router.push('/export')} c={colors}/><Button label='Backup database' onPress={()=>void action(async()=>{const x=await createBackup();Alert.alert('Backup created',`${x.accounts.toLocaleString()} accounts backed up.`);})} c={colors}/><Button label='Restore database' onPress={()=>void action(async()=>{const x=await pickBackup();if(x)setPending(x);})} c={colors}/><Button label='Hard Reset' onPress={()=>setReset(true)} c={colors}/><Text style={{color:colors.textMuted}}>Hard reset deletes local accounts, raw data, images, lists, history, imports and settings.</Text></Section>
<Section title='About' c={colors}><Text style={{color:colors.text}}>Version {APP_VERSION}</Text></Section>
<ConfirmDialog visible={!!pending} colors={colors} title='Restore backup?' message={pending?`${pending.summary.accounts} accounts, ${pending.summary.lists} lists, saved ${pending.summary.exportedAt?formatDateHuman(pending.summary.exportedAt):'unknown'}.`:''} confirmLabel='Restore' destructive onCancel={()=>setPending(null)} onConfirm={()=>void action(async()=>{await restoreBackup(pending);setPending(null);router.replace('/');})}/>
<ConfirmDialog visible={reset} colors={colors} title='Hard Reset' message='This action cannot be undone. It deletes all local accounts, metadata, raw data, images, image records, lists, status history, import history and settings. Type RESET exactly to continue.' confirmLabel='HARD RESET' destructive requireText='RESET' onCancel={()=>setReset(false)} onConfirm={()=>void action(async()=>{await hardResetDatabase();setReset(false);router.replace('/');})}/></ScrollView>}
function Section(p:any){return <View style={{gap:10,marginBottom:8}}><Text style={{color:p.c.textSecondary,fontSize:13,fontWeight:'700'}}>{p.title}</Text><View style={[s.card,{backgroundColor:p.c.surface,borderColor:p.c.border}]}>{p.children}</View></View>}
function Toggle(p:any){return <View style={s.row}><Text style={{color:p.c.text,fontSize:16}}>{p.label}</Text><Switch value={p.value} onValueChange={p.onChange} accessibilityLabel={p.label}/></View>}
function Chips(p:any){return <View style={s.chips}>{p.options.map((o:any)=><Pressable key={o.key} onPress={()=>p.onSelect(o.key)} style={[s.chip,{backgroundColor:p.value===o.key?p.c.primary:p.c.surfaceAlt,borderColor:p.c.border}]}><Text style={{color:p.value===o.key?'#fff':p.c.text,fontWeight:'700'}}>{o.label}</Text></Pressable>)}</View>}
function Button(p:any){return <Pressable onPress={p.onPress} disabled={busyDisabled(p.label)} style={[s.button,{backgroundColor:p.c.surfaceAlt}]}><Text style={{color:p.c.text,fontWeight:'700'}}>{p.label}</Text></Pressable>}function busyDisabled(_:string){return false}
const s=StyleSheet.create({content:{padding:16,paddingBottom:48,gap:10},card:{borderWidth:1,borderRadius:16,padding:14,gap:12},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',minHeight:48},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderRadius:20,padding:12},button:{minHeight:52,borderRadius:12,alignItems:'center',justifyContent:'center'}});
